# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your project files to the container
COPY . .

# Expose the port your Expo development server will run on (usually 19000)
EXPOSE 19000

# Expose additional ports for Metro Bundler (usually 19001) and the Expo DevTools (usually 19002)
EXPOSE 19001
EXPOSE 19002

# Start your Expo development server
CMD ["npm", "start"]
